# WhisperFlow Configuration

# --- Application Settings ---
app:
  lock_file: "/tmp/whisper_flow.lock"

# --- Audio Settings ---
audio:
  samplerate: 16000
  temp_filename: "/tmp/recorded_audio.wav"

# --- Hotkey Settings ---
# See pynput documentation for key names: https://pynput.readthedocs.io/en/latest/keyboard.html
# Example for Super: 'Key.cmd' or 'Key.super'
# Example for Ctrl: 'Key.ctrl'
# Example for Shift: 'Key.shift'
hotkeys:
  ru:
    - "Key.ctrl"
    - "Key.cmd"
  en:
    - "Key.shift"
    - "Key.ctrl"
    - "Key.cmd"

# --- Performance Settings ---
performance:
  # "cuda" or "cpu". Automatically detects CUDA if available.
  device: "auto"
  # For GPU: "float16" (fastest)
  # For CPU: "int8" (balanced)
  compute_type: "auto"
  # See faster-whisper docs for more models: https://github.com/guillaumekln/faster-whisper
  model_size: "large-v3"
  # Beam size for transcription. 1 is fastest, 5 is more accurate.
  beam_size: 3

# --- Transcription Settings ---
transcription:
  # Prompts to guide the model for different languages.
  prompts:
    ru: "Транскрибируй речь точно как услышал. Исправляй грамматические ошибки, английские слова пиши латиницей, ставь знаки препинания. Не добавляй нумерацию, списки или символы в начале. Выводи только сказанные слова."
    en: "Transcribe speech exactly as heard. Correct grammar, use proper punctuation, transcribe technical terms accurately. Do not add numbering, lists, or symbols at the beginning. Output only the spoken words."

# --- Output Settings ---
output:
  paste_tool_timeout: 2 # seconds 